"""
PDF Exporter ΓÇö Generate Styled PDF Reports
=============================================
Creates professional PDF documents from experiment plans
with branded headers, section formatting, and clean typography.

Uses fpdf2 for lightweight PDF generation without LaTeX.
"""

import re
import textwrap
from pathlib import Path
from datetime import datetime
from loguru import logger

try:
    from fpdf import FPDF
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False
    logger.warning("fpdf2 not installed: pip install fpdf2")


class ScientistPDF(FPDF):
    """Custom PDF with AI Scientist branding."""

    # ΓöÇΓöÇ Color palette ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
    BRAND_INDIGO = (79, 70, 229)    # #4F46E5
    BRAND_DARK = (30, 41, 59)       # #1E293B
    BRAND_GRAY = (100, 116, 139)    # #64748B
    BRAND_LIGHT = (241, 245, 249)   # #F1F5F9
    BRAND_GREEN = (16, 185, 129)    # #10B981

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """Branded header on every page."""
        # Logo area ΓÇö indigo bar
        self.set_fill_color(*self.BRAND_INDIGO)
        self.rect(0, 0, 210, 12, style="F")

        # Title text
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.set_y(3)
        self.cell(0, 6, "The AI Scientist | Experiment Plan", align="C")

        self.set_y(18)

    def footer(self):
        """Page number footer."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.BRAND_GRAY)
        date_str = datetime.now().strftime("%Y-%m-%d")
        self.cell(0, 10, f"Generated {date_str}  |  Page {self.page_no()}/{{nb}}", align="C")

    def add_title_page(self, hypothesis: str, novelty_signal: str = ""):
        """Add a professional title page."""
        self.add_page()
        self.alias_nb_pages()

        # Large title
        self.ln(30)
        self.set_font("Helvetica", "B", 28)
        self.set_text_color(*self.BRAND_INDIGO)
        self.cell(0, 15, "Experiment Plan", align="C", new_x="LMARGIN", new_y="NEXT")

        # Subtitle
        self.ln(5)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(*self.BRAND_GRAY)
        self.cell(0, 8, "Generated by The AI Scientist", align="C", new_x="LMARGIN", new_y="NEXT")

        # Divider
        self.ln(10)
        self.set_draw_color(*self.BRAND_INDIGO)
        self.set_line_width(0.8)
        self.line(30, self.get_y(), 180, self.get_y())
        self.ln(10)

        # Hypothesis box
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.BRAND_DARK)
        self.cell(0, 8, "HYPOTHESIS", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        self.set_fill_color(*self.BRAND_LIGHT)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.BRAND_DARK)

        # Word-wrap hypothesis
        hyp_clean = hypothesis.replace("\n", " ").strip()
        self.multi_cell(0, 6, hyp_clean, fill=True)

        # Novelty signal badge
        if novelty_signal:
            self.ln(8)
            self.set_font("Helvetica", "B", 10)
            signal_colors = {
                "not found": self.BRAND_GREEN,
                "similar work exists": (234, 179, 8),  # amber
                "exact match found": (239, 68, 68),     # red
            }
            color = signal_colors.get(novelty_signal, self.BRAND_GRAY)
            self.set_text_color(*color)
            self.cell(0, 8, f"Novelty: {novelty_signal.upper()}", new_x="LMARGIN", new_y="NEXT")

        # Date and metadata
        self.ln(15)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.BRAND_GRAY)
        self.cell(0, 6, f"Date: {datetime.now().strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, "Platform: Hack-Nation x World Bank Youth Summit 2026", new_x="LMARGIN", new_y="NEXT")

    def add_section(self, title: str, content: str):
        """Add a formatted section with title and content."""
        self.add_page()

        # Section header with indigo underline
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*self.BRAND_INDIGO)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")

        self.set_draw_color(*self.BRAND_INDIGO)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(6)

        # Content ΓÇö parse markdown-lite
        self._render_markdown(content)

    def _render_markdown(self, text: str):
        """Render simplified markdown content to PDF."""
        lines = text.split("\n")

        for line in lines:
            stripped = line.strip()

            if not stripped:
                self.ln(3)
                continue

            # H3 headers (###)
            if stripped.startswith("### "):
                self.ln(3)
                self.set_font("Helvetica", "B", 12)
                self.set_text_color(*self.BRAND_DARK)
                header_text = stripped[4:].strip(" #*")
                self.cell(0, 7, header_text, new_x="LMARGIN", new_y="NEXT")
                self.ln(2)
                continue

            # H2 headers (##)
            if stripped.startswith("## "):
                self.ln(4)
                self.set_font("Helvetica", "B", 13)
                self.set_text_color(*self.BRAND_INDIGO)
                header_text = stripped[3:].strip(" #*")
                self.cell(0, 8, header_text, new_x="LMARGIN", new_y="NEXT")
                self.ln(2)
                continue

            # Table rows (|...|)
            if stripped.startswith("|") and "|" in stripped[1:]:
                # Skip separator lines (|---|---|)
                if re.match(r"^\|[\s\-:]+\|", stripped):
                    continue
                self._render_table_row(stripped)
                continue

            # Horizontal rules
            if stripped in ("---", "***", "___"):
                self.ln(2)
                self.set_draw_color(*self.BRAND_LIGHT)
                self.line(10, self.get_y(), 200, self.get_y())
                self.ln(4)
                continue

            # Bullet points
            if stripped.startswith("- ") or stripped.startswith("* "):
                self.set_font("Helvetica", "", 9)
                self.set_text_color(*self.BRAND_DARK)
                bullet_text = stripped[2:]
                # Clean bold markers
                bullet_text = re.sub(r"\*\*(.*?)\*\*", r"\1", bullet_text)
                self.cell(8, 5, chr(8226))  # bullet char
                self.multi_cell(0, 5, bullet_text)
                continue

            # Numbered items
            num_match = re.match(r"^(\d+)\.\s+(.*)", stripped)
            if num_match:
                self.set_font("Helvetica", "", 9)
                self.set_text_color(*self.BRAND_DARK)
                item_text = re.sub(r"\*\*(.*?)\*\*", r"\1", num_match.group(2))
                self.cell(8, 5, f"{num_match.group(1)}.")
                self.multi_cell(0, 5, item_text)
                continue

            # Regular text ΓÇö clean markdown formatting
            clean = re.sub(r"\*\*(.*?)\*\*", r"\1", stripped)
            clean = re.sub(r"\*(.*?)\*", r"\1", clean)
            clean = re.sub(r"`(.*?)`", r"\1", clean)

            self.set_font("Helvetica", "", 9)
            self.set_text_color(*self.BRAND_DARK)
            self.multi_cell(0, 5, clean)

    def _render_table_row(self, row: str):
        """Render a markdown table row."""
        cells = [c.strip() for c in row.split("|")[1:-1]]
        if not cells:
            return

        self.set_font("Helvetica", "", 8)
        self.set_text_color(*self.BRAND_DARK)

        col_width = (190 - 10) / max(len(cells), 1)
        x_start = self.get_x()
        y_start = self.get_y()

        for i, cell in enumerate(cells):
            clean = re.sub(r"\*\*(.*?)\*\*", r"\1", cell)
            clean = re.sub(r"`(.*?)`", r"\1", clean)
            self.set_xy(x_start + i * col_width, y_start)
            self.cell(col_width, 5, clean[:30], border=1)

        self.ln(5)


def export_plan_to_pdf(
    plan_text: str,
    hypothesis: str = "",
    novelty_signal: str = "",
    output_path: str = None,
) -> str:
    """
    Export an experiment plan to a styled PDF.

    Args:
        plan_text: Full plan markdown text
        hypothesis: The hypothesis (for title page)
        novelty_signal: Novelty assessment result
        output_path: Custom output path (auto-generated if None)

    Returns:
        Path to the generated PDF file
    """
    if not PDF_AVAILABLE:
        raise ImportError("fpdf2 is required: pip install fpdf2")

    if not output_path:
        import tempfile
        export_dir = Path(tempfile.gettempdir()) / "ai_scientist_exports"
        export_dir.mkdir(exist_ok=True)
        output_path = str(export_dir / "experiment_plan.pdf")

    pdf = ScientistPDF()

    # Title page
    pdf.add_title_page(hypothesis or "Scientific Hypothesis", novelty_signal)

    # Parse plan into sections
    sections = _split_plan_sections(plan_text)

    if sections:
        for title, content in sections:
            pdf.add_section(title, content)
    else:
        # Fallback: render entire plan as one section
        pdf.add_section("Experiment Plan", plan_text)

    pdf.output(output_path)
    logger.info(f"PDF exported to {output_path}")
    return output_path


def _split_plan_sections(plan_text: str):
    """
    Split a markdown plan into (title, content) sections.

    Splits on ## headers or # headers.
    """
    sections = []
    current_title = None
    current_lines = []

    for line in plan_text.split("\n"):
        stripped = line.strip()

        # Match ## or # headers
        header_match = re.match(r"^#{1,2}\s+(.+)", stripped)
        if header_match:
            # Save previous section
            if current_title and current_lines:
                content = "\n".join(current_lines).strip()
                if content:
                    sections.append((current_title, content))

            current_title = header_match.group(1).strip(" #")
            # Clean emoji from title
            current_title = re.sub(r"^[≡ƒö¼≡ƒº¬≡ƒôï≡ƒº½≡ƒÆ░≡ƒôàΓ£à≡ƒôè]\s*", "", current_title)
            current_lines = []
        else:
            current_lines.append(line)

    # Don't forget last section
    if current_title and current_lines:
        content = "\n".join(current_lines).strip()
        if content:
            sections.append((current_title, content))

    return sections
